enyo.depends(
    "css/pixelism.css",
    "source/pixelism_settings.js",
    "source/ColorPicker.js",
    "source/BrushPicker.js",
    "source/BrushRenderer.js",
    "source/BrushButton.js",
    "source/CropPopup.js",
    "source/canvas.js",
    "source/NagScreen.js",
    "source/Settings.js",
    "source/DrawRegion.js",
    "source/Help.js",
    "source/Main.js"
);
